0.3 frontend fix
Alpha-Serpentis-Developments/Project-Mimic pull request #114
Opened 2021-12-01 23:28 UTC by VulpoTheDev

# This is a Fix PR

Due to miscommunications this PR contains everything but the code that was in the branch before is now in it's own folder called frontend

See #113

2021-12-02 16:04 UTC, AlphaSerpentis requested changes
Check other comment to fix

2021-12-02 16:04 UTC, AlphaSerpentis commented on frontend/package.json
> -  "homepage": "./",
Readd this; it may be important for the production files as the website will be hosted statically on IPFS

2021-12-02 19:14 UTC, VulpoTheDev commented on frontend/package.json
> -  "homepage": "./",
I have reaaded that in commit ff455aa743b9a50600499fd316bf51dc4422b7ce

2021-12-03 14:14 UTC, AlphaSerpentis approved these changes

2021-12-03 14:15 UTC, merged